4 get /api/articles
jaketysome/portfolio-project-news-api pull request #3
Opened 2022-12-12 15:54 UTC by jaketysome

2022-12-12 16:13 UTC, B7Bprog requested changes
Doing well Jake, please see my comments, make the recommended changes and resubmit a pr. 👍

2022-12-12 16:13 UTC, B7Bprog commented on __tests__/app.test.js
> +              expect.objectContaining({
Articles now should have a 'comment_count' property. Please include it in your test and send us a quick pull request with it.

2022-12-12 16:13 UTC, B7Bprog commented on __tests__/app.test.js
> +          expect(articles).toBeInstanceOf(Array);
Is this necessary to check even you are using .forEach() and it only works with arrays?

2022-12-12 16:24 UTC, jaketysome commented on __tests__/app.test.js
> +              expect.objectContaining({
I'm not sure where this comment_count would be coming from?

2022-12-12 16:24 UTC, jaketysome commented on __tests__/app.test.js
> +          expect(articles).toBeInstanceOf(Array);
ok, yes understood!

2022-12-13 08:36 UTC, jaketysome commented on __tests__/app.test.js
> +              expect.objectContaining({
Ignore me actually - I understand where I have gone wrong here - thank you!

2022-12-13 11:21 UTC, closed without merging